# plugins:
#  - jekyll-remote-theme
#    card: summary_large_image
plugins:
  - jemoji # Needed to get emoticon support


#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: Anynomouss/moonwalk
theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
title: Grin for users
description: Grin for muggles and aspiring wizards
